# in EC327, we use the g++ compiler
# therefore, we define the GCC variable
GCC = g++

PA3_Game: Main.o Point2D.o Vector2D.o GameObject.o Building.o PokemonCenter.o PokemonGym.o Pokemon.o Model.o GameCommand.o View.o
	$(GCC) Main.o Point2D.o Vector2D.o GameObject.o Building.o PokemonCenter.o PokemonGym.o Pokemon.o Model.o GameCommand.o View.o -o PA3_Game

# a target to compile the Main.cpp into an object-file
Main.o: Main.cpp
	$(GCC) -c Main.cpp

# a target to compile the Point2D.cpp into an object-file
Point2D.o: Point2D.cpp
	$(GCC) -c Point2D.cpp

# a target to compile the Vector2D.cpp into an object-file
Vector2D.o: Vector2D.cpp
	$(GCC) -c Vector2D.cpp

# the game object class
GameObject.o: GameObject.cpp
	$(GCC) -c GameObject.cpp

# building class inherits GameObject protected methods
Building.o: Building.cpp
	$(GCC) -c Building.cpp

# PokemonCenter class inherits public Building methods
PokemonCenter.o: PokemonCenter.cpp
	$(GCC) -c PokemonCenter.cpp

# PokemonGym class inherits Building methods
PokemonGym.o: PokemonGym.cpp
	$(GCC) -c PokemonGym.cpp

Pokemon.o: Pokemon.cpp
	$(GCC) -c Pokemon.cpp

Model.o: Model.cpp
	$(GCC) -c Model.cpp

GameCommand.o: GameCommand.cpp
	       $(GCC) -c GameCommand.cpp

View.o: View.cpp
	$(GCC) -c View.cpp

# a target to delete all object-files and executables
clean:
	rm PA3_Game *.o *~
